name:                stm-actor
version:             0.1.0.0
github:              "SamuelSchlesinger/stm-actor"
license:             BSD3
author:              "Samuel Schlesinger"
maintainer:          "sgschlesinger@gmail.com"
copyright:           "2019 Samuel Schlesinger"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/SamuelSchlesinger/stm-actor#readme>

dependencies:
- base >= 4.7 && < 5
- mtl
- transformers
- stm
- lifted-base
- transformers-base
- time
- lifted-base
- monad-control

library:
  source-dirs: src

executables:
  example:
    main:                Main.hs
    source-dirs:         example
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - stm-actor
    - containers
    - mtl
    - random

tests:
  stm-actor-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - stm-actor
