{-# LANGUAGE LambdaCase #-}
{-# LANGUAGE StandaloneDeriving #-}
{-# LANGUAGE UndecidableInstances #-}
{-# LANGUAGE MultiParamTypeClasses #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE RankNTypes #-}
{-# LANGUAGE BlockArguments #-}
{-# LANGUAGE DerivingVia #-}
{- |
Module: Control.Concurrent.Actor
Description: Process-local actors with transactional mailboxes
Copyright: (c) Samuel Schlesinger 2020
License: MIT
Maintainer: sgschlesinger@gmail.com
Stability: experimental
Portability: POSIX, Windows

This module provides lightweight, process-local actors backed by STM and
@stm-queue@'s incremental real-time FIFO queues. Each actor owns an unbounded or
bounded mailbox. Sending is an STM operation, so messages can be composed
atomically with application state; a send to a full bounded mailbox retries
until capacity becomes available. Receiving removes one message and runs its
handler in the actor's thread.

An actor has a single lifecycle transition from alive to stopped. The
transition records whether its action completed normally or threw, and
atomically closes checked sends and after-effect registration. 'await' observes
that transition without polling. The completion handler supplied to
'actFinally' and registered after-effects run afterwards in the actor's
terminating thread, with every effect attempted in registration order.

The unchecked 'send' and 'addAfterEffect' operations avoid touching the
lifecycle 'TVar'. Use their checked or non-throwing variants when actor
completion can race the operation.
-}
module Control.Concurrent.Actor
( ActionT
, Actor
, send
, sendChecked
, trySend
, addAfterEffect
, addAfterEffectChecked
, tryAddAfterEffect
, threadId
, livenessCheck
, await
, withLivenessCheck
, Liveness(..)
, ActorDead(..)
, actFinally
, actFinallyBounded
, act
, actBounded
, receiveSTM
, receive
, hoistActionT
, link
, linkSTM
, LinkKill(..)
, self
, murder
, MurderKill(..)
) where

-- This list was generated by compiling with the -ddump-minimal-imports flag.
import Control.Applicative (Alternative)
import Control.Concurrent
    (ThreadId, forkFinally, forkIO, myThreadId, throwTo)
import Control.Concurrent.STM
    ( STM
    , TVar
    , atomically
    , modifyTVar'
    , newTVarIO
    , readTVar
    , retry
    , throwSTM
    , writeTVar
    )
import Control.Exception
    (Exception, SomeException, catch, mask_, throwIO, try)
import Control.Monad.Cont.Class (MonadCont)
import Control.Monad.Error.Class (MonadError)
import Control.Monad.IO.Class (MonadIO(..))
import Control.Monad.IO.Unlift (MonadUnliftIO(..))
import Control.Monad.Reader
    (MonadReader(ask, local), ReaderT(ReaderT))
import Control.Monad.RWS.Class (MonadRWS)
import Control.Monad.State.Class (MonadState)
import Control.Monad.Trans (MonadTrans(..))
import Control.Monad.Writer.Class (MonadWriter)
import Data.Queue (dequeue, enqueue, newBoundedQueue, newQueue)
import Data.Functor.Contravariant (Contravariant(contramap))
import Numeric.Natural (Natural)

-- | A type that contains actions performed by an t'Actor'.
newtype ActionT message m a = ActionT
  { runActionT
    :: ActorContext message
    -> m a
  }

deriving via ReaderT (ActorContext message) m instance Functor m => Functor (ActionT message m)
deriving via ReaderT (ActorContext message) m instance Applicative m => Applicative (ActionT message m)
deriving via ReaderT (ActorContext message) m instance Monad m => Monad (ActionT message m)
deriving via ReaderT (ActorContext message) m instance MonadIO m => MonadIO (ActionT message m)
deriving via ReaderT (ActorContext message) instance MonadTrans (ActionT message)
deriving via ReaderT (ActorContext message) m instance MonadError e m => MonadError e (ActionT message m)
deriving via ReaderT (ActorContext message) m instance MonadWriter w m => MonadWriter w (ActionT message m)
deriving via ReaderT (ActorContext message) m instance MonadState s m => MonadState s (ActionT message m)
deriving via ReaderT (ActorContext message) m instance MonadCont m => MonadCont (ActionT message m)
deriving via ReaderT (ActorContext message) m instance MonadUnliftIO m => MonadUnliftIO (ActionT message m)
deriving via ReaderT (ActorContext message) m instance Alternative m => Alternative (ActionT message m)

instance MonadReader r m => MonadReader r (ActionT message m) where
  ask = ActionT (const ask)
  local f (ActionT ma) = ActionT (fmap (local f) ma)

instance (MonadWriter w m, MonadReader r m, MonadState s m) => MonadRWS r w s (ActionT message m)

data ActorContext message = ActorContext
  { receiveMessage :: STM message
  , actorHandle :: Actor message
  }

data Mailbox message = Mailbox
  { readMailbox :: STM message
  , writeMailbox :: message -> STM ()
  }

-- | A handle used to send messages, inspect lifecycle state, register
-- completion effects, and address the actor's thread.
data Actor message = Actor
  { addAfterEffect' :: AfterEffect -> STM ()
  , threadId' :: ThreadId
  , send' :: message -> STM ()
  , actorState :: TVar ActorState
  }

type Completion = Maybe SomeException

type AfterEffect = Completion -> IO ()

data ActorState
  = Running
  | Stopped Completion

-- | The liveness state of a particular t'Actor'.
data Liveness = Alive | Completed | ThrewException SomeException
  deriving Show

-- | Check the 'Liveness' of a particular t'Actor'.
livenessCheck :: Actor message -> STM Liveness
livenessCheck actor = do
  readTVar (actorState actor) >>= \case
    Running -> pure Alive
    Stopped completion -> pure (maybe Completed ThrewException completion)

-- | Wait until an actor's action has stopped. Unlike 'livenessCheck', this
-- transaction retries while the actor is 'Alive'. It can therefore be composed
-- atomically with other STM operations without polling or sleeping.
--
-- The lifecycle transition happens before the completion handler and
-- after-effects run, so this does not wait for those effects to finish.
--
-- @since 0.4.0.0
await :: Actor message -> STM Liveness
await actor = livenessCheck actor >>= \case
  Alive -> retry
  stopped -> pure stopped

-- | The exception thrown when an operation wrapped in 'withLivenessCheck' is
-- attempted on an actor which has already stopped. 'Nothing' denotes normal
-- completion; 'Just' contains the exception thrown by the actor's action.
data ActorDead = ActorDead (Maybe SomeException)
  deriving Show

instance Exception ActorDead

-- | Allows us to wrap 'addAfterEffect', 'send', and any other custom
-- combinators in a liveness check. This adds contention on the lifecycle
-- 'TVar', but prevents an operation from being accepted after the actor has
-- stopped. If the t'Actor' is 'Completed' or 'ThrewException', this throws an
-- t'ActorDead' exception with 'Nothing' or 'Just' the exception, respectively.
withLivenessCheck :: (Actor message -> x -> STM ()) -> Actor message -> x -> STM ()
withLivenessCheck f actor x = ensureAlive actor >> f actor x

ensureAlive :: Actor message -> STM ()
ensureAlive actor = readTVar (actorState actor) >>= \case
  Running -> pure ()
  Stopped completion -> throwSTM (ActorDead completion)

-- | Once the t'Actor' stops, all of the effects that have been added via
-- this function will run, in registration order. Later effects are still
-- attempted if an earlier effect throws an exception. This is how you can
-- implement your own functions like 'link' or 'linkSTM'. This operation does
-- not itself check liveness; wrap it with 'withLivenessCheck' when registering
-- against an actor that may already have stopped. Registering unchecked after
-- completion stores an effect that can never run.
addAfterEffect :: Actor message -> (Maybe SomeException -> IO ()) -> STM ()
addAfterEffect = addAfterEffect'

-- | Register an after-effect only if the actor is alive. If the actor has
-- already stopped, throw t'ActorDead'. The liveness check and registration are
-- one STM transaction, so actor completion cannot race between them.
--
-- @since 0.4.0.0
addAfterEffectChecked :: Actor message -> (Maybe SomeException -> IO ()) -> STM ()
addAfterEffectChecked = withLivenessCheck addAfterEffect

-- | Attempt to register an after-effect. Return 'False' without registering it
-- if the actor has already stopped.
--
-- @since 0.4.0.0
tryAddAfterEffect :: Actor message -> (Maybe SomeException -> IO ()) -> STM Bool
tryAddAfterEffect = tryWhileAlive addAfterEffect

-- | Retrieve the 'ThreadId' associated with this t'Actor'.
threadId :: Actor message -> ThreadId
threadId = threadId'

-- | Send a message to this t'Actor' without checking its lifecycle. On a
-- bounded actor this transaction retries while the mailbox is full. Sending
-- after completion succeeds when capacity is available, but the message can
-- never be received. An unchecked send already retrying on a full mailbox does
-- not wake merely because the actor stops; use a checked variant when actor
-- completion can race backpressure.
send :: Actor message -> message -> STM ()
send = send'

-- | Send a message only if the actor is alive. If the actor has already
-- stopped, throw t'ActorDead'. The liveness check and enqueue are atomic. On a
-- bounded actor this retries while the mailbox is full; if the actor stops
-- while it is retrying, the transaction wakes and throws t'ActorDead'.
--
-- @since 0.4.0.0
sendChecked :: Actor message -> message -> STM ()
sendChecked = withLivenessCheck send

-- | Attempt to send a message. Return 'False' without enqueueing it if the
-- actor has already stopped. On a live bounded actor this still retries while
-- the mailbox is full: "try" refers to the lifecycle check, not capacity.
--
-- @since 0.4.0.0
trySend :: Actor message -> message -> STM Bool
trySend = tryWhileAlive send

tryWhileAlive :: (Actor message -> x -> STM ()) -> Actor message -> x -> STM Bool
tryWhileAlive f actor x = readTVar (actorState actor) >>= \case
  Running -> f actor x >> pure True
  Stopped _ -> pure False

instance Eq (Actor message) where
  left == right = threadId' left == threadId' right

instance Show (Actor message) where
  show = show . threadId'

instance Contravariant Actor where
  contramap f actor = Actor
    { addAfterEffect' = addAfterEffect' actor
    , threadId' = threadId' actor
    , send' = send' actor . f
    , actorState = actorState actor
    }

-- | Perform some t'ActionT' in a new thread. Once the action stops, record its
-- result, run the supplied completion handler, and then drain all registered
-- after-effects.
actFinally :: (Either SomeException a -> IO ()) -> ActionT message IO a -> IO (Actor message)
actFinally = actFinallyWith newUnboundedMailbox

-- | Like 'actFinally', but use a bounded FIFO mailbox with space for at most
-- the given number of queued messages. Sends retry transactionally while the
-- mailbox is full. The message currently being handled is no longer queued and
-- therefore does not count against this capacity. A capacity of zero creates a
-- mailbox to which no send can commit.
--
-- @since 0.4.0.0
actFinallyBounded
  :: Natural
  -> (Either SomeException a -> IO ())
  -> ActionT message IO a
  -> IO (Actor message)
actFinallyBounded capacity = actFinallyWith (newBoundedMailbox capacity)

actFinallyWith
  :: STM (Mailbox message)
  -> (Either SomeException a -> IO ())
  -> ActionT message IO a
  -> IO (Actor message)
actFinallyWith newMailbox completionHandler (ActionT actionT) = do
  afterEffects <- newTVarIO []
  mailbox <- atomically newMailbox
  stateVar <- newTVarIO Running
  let registerEffect afterEffect = modifyTVar' afterEffects (afterEffect :)
      enqueueMessage = writeMailbox mailbox
      makeActor actorThread = Actor
        { addAfterEffect' = registerEffect
        , threadId' = actorThread
        , send' = enqueueMessage
        , actorState = stateVar
        }
  actorThread <- forkFinally
    (do
      currentThread <- myThreadId
      actionT (ActorContext (readMailbox mailbox) (makeActor currentThread)))
    (finishActor stateVar afterEffects completionHandler)
  pure (makeActor actorThread)

newUnboundedMailbox :: STM (Mailbox message)
newUnboundedMailbox = do
  queue <- newQueue
  pure Mailbox
    { readMailbox = dequeue queue
    , writeMailbox = enqueue queue
    }

newBoundedMailbox :: Natural -> STM (Mailbox message)
newBoundedMailbox capacity = do
  queue <- newBoundedQueue capacity
  pure Mailbox
    { readMailbox = dequeue queue
    , writeMailbox = enqueue queue
    }

finishActor
  :: TVar ActorState
  -> TVar [AfterEffect]
  -> (Either SomeException a -> IO ())
  -> Either SomeException a
  -> IO ()
finishActor stateVar afterEffects completionHandler result = do
  effects <- atomically do
    writeTVar stateVar (Stopped completion)
    registered <- readTVar afterEffects
    writeTVar afterEffects []
    pure (reverse registered)
  runAllEffects (completionHandler result : map ($ completion) effects)
  where
    completion = either Just (const Nothing) result

runAllEffects :: [IO ()] -> IO ()
runAllEffects effects = mask_ (go Nothing effects)
  where
    go :: Maybe SomeException -> [IO ()] -> IO ()
    go firstException [] = maybe (pure ()) throwIO firstException
    go firstException (effect : remaining) = try effect >>= \case
      Left exception -> go (rememberFirst firstException exception) remaining
      Right () -> go firstException remaining

    rememberFirst Nothing exception = Just exception
    rememberFirst remembered _ = remembered

-- | Perform some t'ActionT' in a new thread. Use 'await' to observe when its
-- action stops.
act :: ActionT message IO a -> IO (Actor message)
act = actFinally (const (pure ()))

-- | Like 'act', but use a bounded FIFO mailbox with space for at most the
-- given number of queued messages. See 'actFinallyBounded'.
--
-- @since 0.4.0.0
actBounded :: Natural -> ActionT message IO a -> IO (Actor message)
actBounded capacity = actFinallyBounded capacity (const (pure ()))

-- | Receive a message and do some t'ActionT' with it.
receive :: MonadIO m => (message -> ActionT message m a) -> ActionT message m a
receive f = ActionT \ctx -> do
  message <- liftIO $ atomically (receiveMessage ctx)
  runActionT (f message) ctx

-- | Receive a message and, in the same transaction, produce some result.
receiveSTM :: MonadIO m => (message -> STM a) -> ActionT message m a
receiveSTM f = ActionT \ctx -> liftIO (atomically (receiveMessage ctx >>= f))

-- | Use a natural transformation to transform an t'ActionT' on one base
-- monad to another.
hoistActionT :: (forall x. m x -> n x) -> ActionT message m a -> ActionT message n a
hoistActionT f (ActionT actionT) = ActionT (fmap f actionT)

-- | The exception thrown when an actor we have 'link'ed with stops.
data LinkKill = LinkKill ThreadId
  deriving Show

instance Exception LinkKill

-- | Link the lifetime of the given actor to this one. When the given actor
-- stops, whether normally or exceptionally, it will throw a t'LinkKill'
-- exception to us with its 'ThreadId' attached. Linking to an actor that has
-- already stopped throws the same t'LinkKill' immediately.
link :: MonadIO m => Actor message -> ActionT message' m ()
link you = do
  me <- self
  liftIO $
    atomically (linkSTM me you)
      `catch` \(ActorDead _) -> throwIO (LinkKill (threadId you))

-- | Links the lifetime of the first actor to the second. When the second actor
-- stops, whether normally or exceptionally, it asynchronously throws a
-- t'LinkKill' exception to the first with the second actor's 'ThreadId'
-- attached. If either actor has already stopped, this transaction throws
-- t'ActorDead' instead of installing a link that can never be delivered.
--
-- Link delivery uses a helper thread so a first actor which masks asynchronous
-- exceptions cannot block the second actor's remaining after-effects.
linkSTM :: Actor message -> Actor message' -> STM ()
linkSTM alice bob = do
  ensureAlive alice
  addAfterEffectChecked bob (const (signalLink alice bob))

signalLink :: Actor message -> Actor message' -> IO ()
signalLink alice bob = do
  _ <- forkIO $ throwTo (threadId alice) (LinkKill (threadId bob))
  pure ()

-- | Returns the t'Actor' handle of the actor executing this action.
self :: Applicative m => ActionT message m (Actor message)
self = ActionT (pure . actorHandle)

-- | The exception thrown when we 'murder' an t'Actor'.
data MurderKill = MurderKill ThreadId
  deriving Show

instance Exception MurderKill

-- | Synchronously throw a t'MurderKill' exception to the given t'Actor'. As
-- with 'throwTo', this can block while the target is uninterruptibly masking
-- asynchronous exceptions.
murder :: MonadIO m => Actor message -> m ()
murder actor = liftIO do
  murderer <- myThreadId
  throwTo (threadId actor) (MurderKill murderer)
